# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/profiles/qemu-guest.nix")
  ];

  boot.initrd.availableKernelModules = [
    "ahci"
    "xhci_pci"
    "virtio_pci"
    "sr_mod"
    "virtio_blk"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/1186ea11-93bc-4aca-896f-0188fc36ea78";
    fsType = "ext4";
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/f7739cac-69cf-4bb4-9371-def9e74002ab"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
